[package]
name = "khygl"
version = "0.1.0"
authors = ["khyperia <github@khyperia.com>"]
edition = "2018"

[dependencies]
failure = { version = "", default-features = false, features = ["std"] }
gl = ""
rusttype = ""
